name: Build and Upload node_modules

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安装依赖
        run: npm install
      - name: 打包 node_modules
        run: tar -czf node_modules.tar.gz node_modules
      - name: 上传打包文件
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules.tar.gz
